name: backend-app
replicaCount: 1
image:
  registry: 748624204530.dkr.ecr.ap-south-1.amazonaws.com
  repository: backend-app
  tag: 1736d1d0b18f3dd46432d8ae696cbd935d7a901b
  pullPolicy: IfNotPresent
  resources:
    requests:
      memory: '256Mi'
    limits:
      memory: '512Mi'
service:
  type: ClusterIP
  port: 8080
